developmentseed/observe

app/presets/starter-presets.json, app/screens/Features/SelectFeatureType.js
=> adds a few more starter presets, and sets a clear search placeholder

app/actions/map.js
cc @batpad @LanesGood @sethvincent
=> catch incase file unlink fails

app/screens/Features/AddFeatureDetail.js, app/screens/Features/EditFeatureDetail.js
Fixes #61 
This may have been a regression from the react native upgrade. 
It looks like the function was imported in the parent scope and then subsequently through the props causing a conflict. 
cc @LanesGood @sethvincent @batpad
=> Fix variable scope

app/screens/OfflineMaps/OfflineAreaList.js, app/screens/OfflineMaps/ViewOfflineAreaDetail.js
Fixes scoping for Offline map async functions (same as #62). Closes #65
=> Fix offline map variable scope

app/components/UserContributionsList.js
closes #10 
@LanesGood What do you think of this?
=> Add no contributions screen

__tests__/utils/__snapshots__/edit-utils.test.js.snap, __tests__/utils/edit-utils.test.js
=> test edit utils

__tests__/fixtures/opencage-response.json, __tests__/setup/mock.js, __tests__/utils/__snapshots__/get-feature-fields.test.js.snap, __tests__/utils/__snapshots__/get-fields.test.js.snap, __tests__/utils/get-feature-fields.test.js, __tests__/utils/get-fields.test.js, __tests__/utils/get-place-name.test.js, __tests__/utils/get-taginfo.test.js
=> More util tests

__tests__/fixtures/osm-xml-for-quadkey.xml, __tests__/fixtures/way-343446026/node-3502789251.xml, __tests__/fixtures/way-343446026/node-3502789252.xml, __tests__/fixtures/way-343446026/node-3502789253.xml, __tests__/fixtures/way-343446026/node-3502789254.xml, __tests__/fixtures/way-343446026/way-343446026.xml, __tests__/services/__snapshots__/api.test.js.snap, __tests__/services/api.test.js
=> More API tests

app/screens/OfflineMaps/ViewOfflineAreaDetail.js
fixes #72 
cc @batpad @sethvincent
=> use proper asset url for ios and android

app/screens/Features/AddFeatureDetail.js
=> return to feature select screen from adding a point

app/screens/UserContributions/UserContributionsListScreen.js
=> hide the upload all and delete all buttons if there are no edits

app/components/RecordHeader.js, app/screens/Explore.js, app/selectors/index.js, app/style/map.js
=> show gps track while recording

app/screens/UserContributions/UserContributionsListScreen.js
Fixes https://github.com/developmentseed/observe/issues/20
=> hide upload and trash buttons if there are no edits

app/components/PageWrapper.js, app/screens/Features/AddFeatureDetail.js, app/screens/Features/EditFeatureDetail.js, package.json, yarn.lock
=> scroll the screen to avoid keyboard overlapping input fields

app/screens/Features/SelectFeatureType.js
Fixes https://github.com/developmentseed/observe/issues/9
=> clear search text on blur

package.json, yarn.lock
I was having build issues and updating @react-native-mapbox-gl/maps resolved them. 
<details>
<summary>The error output I was seeing</summary>
<pre>
> Task :@react-native-mapbox-gl_maps:compileDebugJavaWithJavac FAILED
/Users/sdv/workspace/developmentseed/observe/node_modules/@react-native-mapbox-gl/maps/android/rctmgl/src/main/java/com/mapbox/rctmgl/utils/ResourceUtils.java:6: error: package android.support.v4.content does not exist
import android.support.v4.content.ContextCompat;
^
/Users/sdv/workspace/developmentseed/observe/node_modules/@react-native-mapbox-gl/maps/android/rctmgl/src/main/java/com/mapbox/rctmgl/components/camera/RCTMGLCamera.java:44: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
^ …
=> update @react-native-mapbox-gl/maps to ^7.0.8

app/actions/camera.js, app/components/PhotoGrid.js, app/screens/CameraScreen.js, app/screens/Explore.js, app/screens/Features/EditFeatureDetail.js, app/screens/Features/ViewFeatureDetail.js, app/screens/Photos/PhotoDetailScreen.js, app/screens/Photos/PhotosListScreen.js, app/utils/photos.js
=> add photos to a feature

app/components/ConfirmDialog.js, app/components/Header.js, app/screens/Explore.js
=> allow the user to discard invalid trace

README.md, docs/user-guide.md
This PR addresses basic documentation and revises the user manual for the upcoming release candidate.
=> Revise documentation

app/services/observe-api.js
Needed because of https://github.com/react-native-community/react-native-camera/pull/1776
cc @geohacker @vgeorge
=> replace newline chars in base64 string

app/actions/camera.js, app/actions/traces.js, app/components/PhotosItem.js, app/components/TracesItem.js, app/reducers/camera.js, app/reducers/traces.js, app/services/observe-api.js
Fixes #148 
also show this in the list.
=> store uploadedAt timestamp for traces and photos

app/screens/Photos/PhotosListScreen.js
=> make photo list sort consistent

app/components/PhotosItem.js, app/components/TracesItem.js, app/reducers/camera.js, app/reducers/traces.js
=> pending edit upload status for photos and traces

app/components/MegaMenu.js, app/screens/Explore.js
I've started pulling megamenu into its own component, but am aware that the actions are more complicated than I've drafted here. Would welcome the opportunity to see how this should be done properly. @sethvincent or @vgeorge would you be willing to pair on this? My current code is not yet functional.
Will close #190
=> Megamenu component

app/screens/Explore.js
=> Make sure explore mode is set after offline hijacks the map for bbox

app/screens/Features/SelectFeatureType.js, app/utils/map-modes.js
Once we integrate this, we want to add starter presets also for ways. cc @sethvincent 
Fixes #192
=> Support ways on select preset screen

docs/debugging.md, docs/macos-setup.md
Small updates in setting up a local development enviroment. Removed some instructions for Android as they are already included in React Native documentation.
=> Updates in docs

app/screens/Explore.js, app/style/map.js
Creates separate styles for editing and selected features.
=> Improve styles

app/actions/wayEditing.js
The commit 739cd5f50ca806fdd69ea99783f032367c16f629 added a regression when trying to add a new way.
=> Fix "add way" regression

__tests__/utils/__snapshots__/nearest.test.js.snap, app/actions/wayEditingHistory.js, app/reducers/wayEditingHistory.js, app/selectors/index.js, app/utils/modify-shared-ways.js, app/utils/nearest.js
=> add a new node to an existing way

app/actions/wayEditing.js
When editing a way, fetching member nodes from the nodecache so the membership to the way is captured. Converting the coordinates won't preserve membership to other ways. 
cc @vgeorge @sethvincent
=> fetch member nodes from the nodecache

app/style/map.js
This PR adds the app color theme to OSM features on the map. Goal here was to align with the mockup, make the app brand colors more dominant, and emphasize selected over background features. To review: color selection, ability to distinguish actions and feature types.
=> Update map color variables

app/utils/get-preset-by-tags.js
In the previous logic presets with high `matchScore` property ended up with value equal to 1, even if they didn't match. Did a refactor based on iD code, it seems to be working as supposed now.
=> Fix getPresetByTags()

app/actions/map.js, app/components/FeatureDetailHeader.js, app/components/FeatureRelationErrorDialog.js, app/components/FeatureRelationWarning.js, app/components/WayEditingOverlay.js, app/reducers/map.js, app/screens/Explore.js, app/screens/Features/ViewFeatureDetail.js
this pr shows a warning when a user selects a feature that is in a relation, restricts operations: changing preset, deleting the feature, or deleting or merging nodes in a way. a message is shown in a dialog any time a user tries to perform one of those operations.
=> prototype of feature in relation warning

app/components/FeatureDetailHeader.js, app/screens/Explore.js
Fixes #245 
cc @LanesGood @vgeorge
=> Edit geometry of a point

app/reducers/wayEditingHistory.js, app/utils/modify-shared-ways.js
fixes #252 
@batpad - pointing this to your changesets PR. Feel free to merge if this looks good to you.
=> add source and destination to merged nodes

app/components/FeatureDetailHeader.js, app/screens/Features/EditFeatureDetail.js, app/screens/Features/ViewFeatureDetail.js, app/utils/edits-to-geojson.js
Addresses #278. I also changed the action text for editing the geometry.
=> Change "View Feature Detail" screen title

app/reducers/wayEditingHistory.js, app/utils/modify-shared-ways.js
=> Fix delete nodes

app/actions/wayEditing.js, app/actions/wayEditingHistory.js, app/components/WayEditingOverlay.js, app/reducers/wayEditingHistory.js, app/screens/Explore.js, app/selectors/index.js, app/utils/create-way-feature.js, app/utils/edit-to-osm-change.js, app/utils/modify-shared-ways.js, app/utils/nearest.js, app/utils/nodes-to-geojson.js, app/utils/utils.js
=> Allow editing ways that are pending upload

app/components/FeatureDetailHeader.js
See #259. 
At this point the second item was implemented, component FeatureDetailsHeader was changed to not allow editing of feature type other that "Point" or "LineString".
=> Fix Edit Geometry button

docs/user-guide.md
Still in progress - adding more screenshots and gifs of new/updated functionality and UI
=> Initial user guide update with new UI

app/screens/Explore.js
@LanesGood this now hides a node when it's deleted from the map, might partly help with #296.
=> Hide deleted nodes

app/components/Header.js
=> Update invalid trace message

app/screens/Features/EditFeatureDetail.js
=> Clear way after edit

app/actions/edit.js, app/utils/edit-to-osm-change.js, app/utils/edits-to-geojson.js, app/utils/utils.js
Flags and deletes invalid Polygons in additions to LineStrings
TODO:
- Of the remaining nodes on the invalid object, delete the nodes if they are orphaned.
cc @geohacker
=> flag invalid lines and polygons and delete them

app/reducers/wayEditingHistory.js
This fixes #321 
cc @LanesGood
=> remove newly added nodes from the nodes collection
